### ISSUE TITLE
Cannot vote from Android App

### ISSUE THREAD

**Issue by vicnevicne** [devoxx/AndroidMobileApp#22]
I'm always getting a "Something went wrong..." message each time I try to vote :-(

**Comment by jmodrako** [comment]
Hello @vicnevicne Thanks for the info, I've fixed this bug few minutes ago, and I've published new version on Play Store, now it's required 1-2hrs to be available as update.

Fixed in https://github.com/devoxx/AndroidMobileApp/issues/16

**Comment by vicnevicne** [comment]
Thanks for the express fix. Update is still not proposed, but I will check tomorrow morning. KR.

**Comment by vicnevicne** [comment]
Had to uninstall and reinstall to get new version, but I lost all my schedule :-(.
After that I could vote yesterday and today just giving stars, but now I just spent 10 minutes writing detailed feedback on a talk and... "Something went wrong."
Poof. lost everything :-(

**Comment by jmodrako** [comment]
Sorry about that @vicnevicne It was a way to nod lost your data, (Clear scanned QR in settings, and then rescan it). I've written this in some of the issues about voting. I will do my best to avoid such bugs!

**Comment by vicnevicne** [comment]
Yeah, no problem for the profile, I re-selected my favourites.
But still, with the new version, I could vote without leaving a comment, but my vote that included a (rather lengthy) comment was dropped with a "something went wrong"...
